### ISSUE TITLE
Jar file

### ISSUE THREAD

**Issue by M4Gn1T** [EconomyS/EconomyLand#1]
@onebone 
Where i can download jar file? I tru to build it with this (https://github.com/EconomyS/EconomyLand#build) but nothing happens
Could you please uplod it to your jenkins?

**Comment by M4Gn1T** [comment]
@onebone I want help you with translation, but I need jar file

**Comment by onebone** [comment]
http://jenkins.onebone.me/job/EconomyLand/lastBuild/me.onebone$EconomyLand/artifact/me.onebone/EconomyLand/1.0.0/EconomyLand-1.0.0.jar
